export const GET_FLIGHTS_REQUEST = 'GET_FLIGHTS_REQUEST'
export const GET_FLIGHTS_SUCCESS = 'GET_FLIGHTS_SUCCESS'
export const GET_FLIGHTS_FAIL = 'GET_FLIGHTS_FAIL'
export const LIST_FLIGHTS_RESET = 'LIST_FLIGHTS_RESET'


