export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'
export const CREATE_ORDER_RESET = 'CREATE_ORDER_RESET'

export const GET_ORDER_DETAILS_REQUEST = 'GET_ORDER_DETAILS_REQUEST'
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS'
export const GET_ORDER_DETAILS_FAIL = 'GET_ORDER_DETAILS_FAIL'

export const PAY_ORDER_REQUEST = 'PAY_ORDER_REQUEST'
export const PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS'
export const PAY_ORDER_FAIL = 'PAY_ORDER_FAIL'
export const PAY_ORDER_RESET = 'PAY_ORDER_RESET'

export const LIST_MY_ORDERS_REQUEST = 'LIST_MY_ORDERS_REQUEST'
export const LIST_MY_ORDERS_SUCCESS = 'LIST_MY_ORDERS_SUCCESS'
export const LIST_MY_ORDERS_FAIL = 'LIST_MY_ORDERS_FAIL'
export const LIST_MY_ORDERS_RESET = 'LIST_MY_ORDERS_RESET'


export const LIST_ORDERS_REQUEST = 'LIST_ORDERS_REQUEST'
export const LIST_ORDERS_SUCCESS = 'LIST_ORDERS_SUCCESS'
export const LIST_ORDERS_FAIL = 'LIST_ORDERS_FAIL'


export const DELIVER_ORDER_REQUEST = 'DELIVER_ORDER_REQUEST'
export const DELIVER_ORDER_SUCCESS = 'DELIVER_ORDER_SUCCESS'
export const DELIVER_ORDER_FAIL = 'DELIVER_ORDER_FAIL'
export const DELIVER_ORDER_RESET = 'DELIVER_ORDER_RESET'
