export const REQUEST_USER_LOGIN = 'REQUEST_USER_LOGIN'
export const SUCCESS_USER_LOGIN = 'SUCCESS_USER_LOGIN'
export const FAILURE_USER_LOGIN = 'FAILURE_USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'

export const REQUEST_USER_REGISTER = 'REQUEST_USER_REGISTER'
export const SUCCESS_USER_REGISTER = 'SUCCESS_USER_REGISTER'
export const FAILURE_USER_REGISTER = 'FAILURE_USER_REGISTER'

export const REQUEST_USER_DETAILS = 'REQUEST_USER_DETAILS'
export const SUCCESS_USER_DETAILS = 'SUCCESS_USER_DETAILS'
export const FAILURE_USER_DETAILS = 'FAILURE_USER_DETAILS'
export const RESET_USER_DETAILS = 'RESET_USER_DETAILS'

export const REQUEST_USER_UPDATE_PROFILE = 'REQUEST_USER_UPDATE_PROFILE'
export const SUCCESS_USER_UPDATE_PROFILE = 'SUCCESS_USER_UPDATE_PROFILE'
export const FAILURE_USER_UPDATE_PROFILE = 'FAILURE_USER_UPDATE_PROFILE'
export const RESET_USER_UPDATE_PROFILE = 'RESET_USER_UPDATE_PROFILE'


export const REQUEST_USER_LIST = 'REQUEST_USER_LIST'
export const SUCCESS_USER_LIST = 'SUCCESS_USER_LIST'
export const FAILURE_USER_LIST = 'FAILURE_USER_LIST'
export const RESET_USER_LIST = 'RESET_USER_LIST'

export const REQUEST_USER_DELETE = 'REQUEST_USER_DELETE'
export const SUCCESS_USER_DELETE = 'SUCCESS_USER_DELETE'
export const FAILURE_USER_DELETE = 'FAILURE_USER_DELETE'

export const REQUEST_USER_UPDATE = 'REQUEST_USER_UPDATE'
export const SUCCESS_USER_UPDATE = 'SUCCESS_USER_UPDATE'
export const FAILURE_USER_UPDATE = 'FAILURE_USER_UPDATE'
export const RESET_USER_UPDATE = 'RESET_USER_UPDATE'
