# Generated by Django 4.2.4 on 2023-10-14 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_orderitem_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='coutry',
            new_name='country',
        ),
    ]
