# Generated by Django 4.2.4 on 2023-10-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_shippingaddress_shippingprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliviredAt',
            new_name='deliveredAt',
        ),
    ]
