# Generated by Django 4.2.4 on 2023-10-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_deliviredat_order_deliveredat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder-image.png', null=True, upload_to=''),
        ),
    ]
